name: Build and Push to ACR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: self-hosted
    
    env:
      IMAGE_NAME: todo-delete-tasks-api
      IMAGE_TAG: v1
      ACR_NAME: acrrg3
      ACR_LOGIN_SERVER: acrrg3.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name acrrg3

      - name: Build Docker Image
        run: |
          docker build -t todo-delete-tasks-api:v1 ./DeleteTaskTodoMicroservice

      - name: Tag Docker Image for ACR
        run: |
          docker tag todo-delete-tasks-api:v1 acrrg3.azurecr.io/todo-delete-tasks-api:v1

      - name: Push Docker Image to ACR
        run: |
          docker push acrrg3.azurecr.io/todo-delete-tasks-api:v1